New settings for Jearduino

diff --git a/simulators/jearduino/searduino-jearduino.sh.tmpl b/simulators/jearduino/searduino-jearduino.sh.tmpl
--- a/simulators/jearduino/searduino-jearduino.sh.tmpl
+++ b/simulators/jearduino/searduino-jearduino.sh.tmpl
@@ -19,11 +19,33 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+
+read_file()
+{
+    FILE=$1
+    if [ -f ${FILE} ]
+    then
+	. ${FILE}
+    else
+	echo "Can't find file: $FILE"
+	exit 1
+    fi
+}
+
+SEARDUINO_PATH=__INSTALL_DIR__
+SEARDUINO_SHARE=${SEARDUINO_PATH}/share/searduino/
+read_file ${SEARDUINO_SHARE}/scripts/settings
+read_file ${SEARDUINO_SHARE}/scripts/functions
+
+
 export PATH=__INSTALL_DIR__/bin:${PATH}
 export LD_LIBRARY_PATH=__INSTALL_DIR__/lib
 export JAVA_LIBRARY_PATH=__INSTALL_DIR__/lib
 
+
 java -cp ${JAVA_LIBRARY_PATH}/Searduino.jar:${JAVA_LIBRARY_PATH}/Jearduino.jar\
+     -Dsearduino.dir=${SEARDUINO_PATH} \
+     -Dsearduino.project.dir=${SEARDUINO_PROJECT_DIR} \
+     -Dsearduino.arduinoex.dir=${ARDUINO_INO_EX} \
      -Djava.library.path=${JAVA_LIBRARY_PATH} \
       com.sandklef.jearduino.Jearduino $*
-
