removed man-creator

diff --git a/simulators/jearduino/searduino-jearduino.sh.tmpl b/simulators/jearduino/searduino-jearduino.sh.tmpl
--- a/simulators/jearduino/searduino-jearduino.sh.tmpl
+++ b/simulators/jearduino/searduino-jearduino.sh.tmpl
@@ -49,30 +49,6 @@ export JAVA_ARGS=" $JAVA_ARGS      -Dsearduino.arduinoex.dir=${ARDUINO_INO_EX}"
 export JAVA_ARGS=" $JAVA_ARGS      -Djava.library.path=${JAVA_LIBRARY_PATH}"
 export JAVA_ARGS=" $JAVA_ARGS      com.sandklef.jearduino.Jearduino"
 
-nroff() {
-    SEARD_HELP=/tmp/searduino-help.txt
-    java ${JAVA_ARGS} --help > ${SEARD_HELP}
-    
-    TITLE=$(head -1 ${SEARD_HELP} | awk '{ print $1}')
-    DESCRIPTION=$(head -1 ${SEARD_HELP} | awk '{ print $1}')
-    echo ".TH $TITLE 1"
-    echo ".SH NAME"
-    head -1 ${SEARD_HELP} | sed 's,\-,\\\-,g'
-    echo .SH SYNOPSIS
-    echo  $(basename $0)  [OPTIONS]
-    echo .SH OPTIONS
-    echo .TP
-    awk '{  if ( $1 ~ /OPTIONS/ ) { SYN=1; } else { if (SYN==1) { printf "%s\n", $0; } } }' ${SEARD_HELP} | while(true)
-    do
-        read OPT
-        read OPT_DESC
-        read EMPTY
-        echo ".B $OPT"
-        echo " $OPT_DESC"
-        echo .TP
-        if [ "$OPT" = "" ] ; then break; fi
-    done
-}
 
 if [ "$1" = "--nroff" ]
 then
@@ -82,7 +58,12 @@ then
         echo "Missing name for MAN page"
         exit 1
     fi
-    nroff > $MAN
+    . ../../scripts/man-support
+    SEARD_HELP=/tmp/searduino-help.txt
+    java ${JAVA_ARGS} --help > ${SEARD_HELP}
+    if [ "$?" != "0" ] || [ ! -s ${SEARD_HELP} ]; then echo "Failed generating help file for nroff" ; exit 1; fi
+    gen_nroff ${SEARD_HELP}  > $MAN
+    if [ "$?" != "0" ] ; then echo "Failed creating Man file" ; exit 1; fi
     
     exit 0
 else
