Generating nroff (Man page needed at Chalmers)

diff --git a/simulators/jearduino/searduino-jearduino.sh.tmpl b/simulators/jearduino/searduino-jearduino.sh.tmpl
--- a/simulators/jearduino/searduino-jearduino.sh.tmpl
+++ b/simulators/jearduino/searduino-jearduino.sh.tmpl
@@ -42,10 +42,49 @@ export PATH=__INSTALL_DIR__/bin:${PATH}
 export LD_LIBRARY_PATH=__INSTALL_DIR__/lib
 export JAVA_LIBRARY_PATH=__INSTALL_DIR__/lib
 
-
-java -cp ${JAVA_LIBRARY_PATH}/Searduino.jar:${JAVA_LIBRARY_PATH}/Jearduino.jar\
+JAVA_ARGS=-cp ${JAVA_LIBRARY_PATH}/Searduino.jar:${JAVA_LIBRARY_PATH}/Jearduino.jar\
      -Dsearduino.dir=${SEARDUINO_PATH} \
      -Dsearduino.project.dir=${SEARDUINO_PROJECT_DIR} \
      -Dsearduino.arduinoex.dir=${ARDUINO_INO_EX} \
      -Djava.library.path=${JAVA_LIBRARY_PATH} \
-      com.sandklef.jearduino.Jearduino $*
+     com.sandklef.jearduino.Jearduino
+
+nroff() {
+    SEARD_HELP=/tmp/searduino-help.txt
+    java ${JAVA_ARGS} --help > ${SEARD_HELP}
+    
+    TITLE=$(head -1 ${SEARD_HELP} | awk '{ print $1}')
+    DESCRIPTION=$(head -1 ${SEARD_HELP} | awk '{ print $1}')
+    echo ".TH $TITLE 1"
+    echo ".SH NAME"
+    head -1 ${SEARD_HELP} | sed 's,\-,\\\-,g'
+    echo .SH SYNOPSIS
+    echo  $(basename $0)  [OPTIONS]
+    echo .SH OPTIONS
+    echo .TP
+    awk '{  if ( $1 ~ /OPTIONS/ ) { SYN=1; } else { if (SYN==1) { printf "%s\n", $0; } } }' ${SEARD_HELP} | while(true)
+    do
+        read OPT
+        read OPT_DESC
+        read EMPTY
+        echo ".B $OPT"
+        echo " $OPT_DESC"
+        echo .TP
+        if [ "$OPT" = "" ] ; then break; fi
+    done
+}
+
+if [ "$1" = "--nroff" ]
+then
+    MAN=$2
+    if [ "$MAN" = "" ]
+    then
+        echo "Missing name for MAN page"
+        exit 1
+    fi
+    nroff > $MAN
+    
+    exit 0
+else
+    java ${JAVA_ARGS} $*
+fi
